[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[rpc_endpoints]
hyper_evm_testnet = "https://rpc.hyperliquid-testnet.xyz/evm"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
